### ISSUE TITLE
Add checksum to meta?

### ISSUE THREAD

**Issue by biovoid** [dlbeer/dhara#6]
Hi,
Is it possible to write checksum of the writted/read page to the meta block? Some memory chips does not contain extra space (or hardware option) for ecc. I see how to protect the journal with magic, just make ie crc16 into frist two bytes of the page_buf. But i'm not sure if possible to use meta for this purpose.

**Comment by dlbeer** [comment]
biovoid <notifications@github.com> writes:
> Is it possible to write checksum of the writted/read page to the
> meta block? Some memory chips does not contain extra space (or
> hardware option) for ecc. I see how to protect the journal with magic,
> just make ie crc16 into frist two bytes of the page_buf. But i'm not
> sure if possible to use meta for this purpose.

What NAND chips are you using that don't have an OOB area?

A CRC on the metadata wouldn't be that helpful -- it would only detect
errors in metadata (not user pages) and it wouldn't allow you to correct
them. Your only option on detecting an error would be to halt or to
reinitialize the journal.

If you really didn't have OOB, you could fake it by having your NAND
layer setting aside a certain number of blocks to use for ECC data and
writing them in parallel with the real data. You'll be able to do this
even if one block is used for ECC on more than one real block, because
dhara guarantees to write blocks sequentially -- it won't go back and
rewrite earlier blocks until its used all of the other blocks in the
group.

Cheers,
Daniel

--
Daniel Beer <dlbeer@gmail.com> http://dlbeer.co.nz/
PGP: BA6E 0B26 1F89 246C E3F3  C910 1E58 C43A 160A 553B

**Comment by biovoid** [comment]
I am using FL256LAMF01 that don't have ECC (like FL256S) and don't have additional space for OOB. My goal in this case was not to correct errors but restore some previous synced checkpoint, to save consistency of the filesystem.

**Comment by dlbeer** [comment]
biovoid <notifications@github.com> writes:
>    I am using FL256LAMF01 that don't have ECC (like FL256S) and don't have
>    additional space for OOB. My goal in this case was not to correct errors
>    but restore some previous synced checkpoint, to save consistency of the
>    filesystem.

This chip is NOR flash, not NAND. It doesn't have OOB data because the
intrinsic bit error rate is low enough not to worry (in theory, at
least). It already has re-writable sectors with a large endurance, so
the only really useful thing you'd get from dhara is atomic rewrites and
possibly wear levelling if you plan on rewriting logical sectors more
than the endurance limit.

If you wanted to proceeed then I think the best way would be to set
aside a certain number of pages for storing checksums and handle this in
the flash driver layer, as per the previous message.

Regarding filesystem consistency -- I'm not sure that dhara will do
exactly what you want here. The synchronization points are not wholly
user-specified. You can create a synchronization point manually, but
they will also occur automatically, and on failure, the most recent
point is what's restored. This might not be what you're expecting, and
you probably can't use it as-is to guarantee filesystem consistency.

Cheers,
Daniel

--
Daniel Beer <dlbeer@gmail.com> http://dlbeer.co.nz/
PGP: BA6E 0B26 1F89 246C E3F3  C910 1E58 C43A 160A 553B
